image:
  name: saschpe/android-ndk:35-jdk17.0.12_7-ndk27.0.12077973-cmake3.22.1

stages:
  - assembleDebug
  - assembleRelease
  - changelogDev
  - changelogRelease
  - deployRelease
  - sonar

assembleDebug:
  interruptible: true
  stage: assembleDebug
  only:
    - dev
    - merge_request
  script:
    - cat $GOOGLE_SERVICES_JSON > app/google-services.json
    - echo -e "STORE_FILE=${KEYSTORE_FILE}\nSTORE_PASSWORD=${KEYSTORE_PASSWORD}\nKEY_ALIAS=${KEYSTORE_ALIAS}\nKEY_PASSWORD=${KEYSTORE_PASSWORD}" > app/keys/keystore.properties
    - cat app/keys/keystore.properties
    - chmod +x ./gradlew
    - ./gradlew :app:assembleDebug

assembleRelease:
  interruptible: true
  stage: assembleRelease
  only:
    - /^release\/.*$/
  script:
    - cat $GOOGLE_SERVICES_JSON > app/google-services.json
    - echo -e "STORE_FILE=${KEYSTORE_FILE}\nSTORE_PASSWORD=${KEYSTORE_PASSWORD}\nKEY_ALIAS=${KEYSTORE_ALIAS}\nKEY_PASSWORD=${KEYSTORE_PASSWORD}" > app/keys/keystore.properties
    - cat app/keys/keystore.properties
    - chmod +x ./gradlew
    - ./gradlew :app:assembleRelease
  artifacts:
    expire_in: 1 week
    name: "release$(date +\"%Y-%m-%d_%H-%M\")"
    paths:
      - app/build/outputs/apk/release/

changelogDev:
  stage: changelogDev
  only:
    - dev
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [ "" ]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - cat $GIT_CLIFF_DEV_CONFIG > cliff-dev.toml
    - git-cliff -c cliff-dev.toml --latest -r . > cliff.txt
    - cat cliff.txt | head -n -2 > catlog.txt
    - awk '!x[$0]++' catlog.txt > CHANGELOG.txt
    - cat CHANGELOG.txt
  artifacts:
    paths:
      - CHANGELOG.txt

changelogRelease:
  stage: changelogRelease
  only:
    - /^release\/.*$/
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [ "" ]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - cat $GIT_CLIFF_RELEASE_CONFIG > cliff-release.toml
    - git-cliff -c cliff-release.toml --latest -r . > cliff.txt
    - cat cliff.txt | head -n -2 > catlog.txt
    - awk '!x[$0]++' catlog.txt > CHANGELOG.txt
    - cat CHANGELOG.txt
  artifacts:
    paths:
      - CHANGELOG.txt

deployRelease:
  stage: deployRelease
  image:
    name: andreysenov/firebase-tools
  only:
    - /^release\/.*$/
  dependencies:
    - changelogRelease
    - assembleRelease
  script:
    - firebase appdistribution:distribute ./app/build/outputs/apk/release/app-release.apk --app $FIREBASE_APP_ID
      --groups "qa-internal"
      --token "$FIREBASE_TOKEN"
      --release-notes "RELEASE BUILD\n\n$(cat CHANGELOG.txt)"

sonarqube-check:
  stage: sonar
  only:
    - dev
    - merge_requests
    - main
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true